name: eagle_eye
description: "EagleEye is a Dart CLI tool provided by CodandoTV for detecting architecture violations in Dart projects."
homepage: "https://github.com/CodandoTV/eagle-eye"

version: 2.0.0

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^7.7.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.25.7
